name: PROD Deploy (Auto)

on:
  pull_request:
    branches:
      - prod
    types:
      - closed

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PROD branch
        uses: actions/checkout@v3
        with:
          ref: prod
          fetch-depth: 0 # 태그를 모두 보기 위해 필요

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> .env
          echo "GIST_URL=${{ secrets.GIST_URL }}" >> .env

      - name: Determine deploy type
        id: determine
        run: |
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"

          if [[ "$HEAD_BRANCH" == "qa" ]]; then
            echo "deploy_type=release" >> $GITHUB_ENV
          elif [[ "$HEAD_BRANCH" =~ ^[0-9]+-hotfix/.*$ ]]; then
            echo "deploy_type=hotfix" >> $GITHUB_ENV
          else
            echo "❌ 예상하지 못한 브랜치: $HEAD_BRANCH"
            exit 1
          fi

      - name: Determine PROD version
        id: version
        run: |
          git fetch --tags

          if [[ "$deploy_type" == "release" ]]; then
            LATEST=$(git tag --list "qa-v*" --sort=-v:refname | head -n 1)
            echo "Latest QA tag: $LATEST"

            if [[ "$LATEST" == "" ]]; then
              VERSION="1.0.0"
            else
              VERSION="${LATEST#qa-}" 
            fi

          elif [[ "$deploy_type" == "hotfix" ]]; then
            LATEST=$(git tag --list "v*" --sort=-v:refname | head -n 1)
            echo "Latest PROD tag: $LATEST"

            if [[ "$LATEST" == "" ]]; then
              VERSION="1.0.0"
            else
              IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST#v}"
              PATCH=$((PATCH + 1))
              VERSION="$MAJOR.$MINOR.$PATCH"
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "📌 Final version to tag: $VERSION"

      - name: Create Git Tag (vX.X.X)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push PROD Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nextjs-docker
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY
          echo "📦 Building ECR image: $IMAGE:prod-$VERSION"

          docker build -f Dockerfile \
            -t $IMAGE:prod-$VERSION \
            -t $IMAGE:prod-latest .

          docker push $IMAGE:prod-$VERSION
          docker push $IMAGE:prod-latest
