name: Dummy Version update

on:
  pull_request:
    types: [labeled]

jobs:
  version-update:
    name: version-update-check ✅
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello! version update test"
